### PR TITLE
Let types specify a display format

### PR DESCRIPTION
**Pull request by dovrosenberg**
It can be helpful (think forms) to have display formats associated with each type.  I could do this with a behavior, but it seemed better to integrate it with types so that you only need to define the formatter function once (in the type definition).

Not sure if there's a simpler way to implement this, but here it is, if you're interested.

To the developer, the changes are:

Inside type definition, can add an attribute 'display':

    Astro.createType({
        name: 'currency',
        cast: ...
        display: function(value) { return accounting.formatMoney(value); }
    });

If I have a field 'dollars' with type 'currency', I can then simply do:

    obj.getDisplay('dollars') 

to get the properly formatted version.  `getDisplay` also supports requesting via the other fieldOrPattern styles.

You can also take a parameter argument in `display()` and pass it in `getDisplay()`, for example to specify a number of decimal points:

    obj.getDisplay('dollars',2);

If you like it, I can update the documentation for types, as well.

### CODE REVIEW

**Comment by jagi** [comment]
Hmm I don't know if it's good idea to mess with types in this way. Number formatting is something more related with VIEW layer than MODEL. Type is type. Currency is still of number type. I see TYPES more like something that it's not of other already defined type. Let's take for example imaginary number, address (combination  of city and state), geolocation etc.

What I would suggest is creating conctructor Currency which would have getFormatted function. It would store number.

```js
Currency = function(n) {
  this.amount = n;
};

Currency.prototype.getFormatted = function(params) {
};
```

And this type would be registered so you could do as follows.

```js
obj.get('price').getFormatted(2)
```

What do you think? You could create behavior and that would be imho better. Let me know what you think.

**Comment by dovrosenberg** [comment]
I don't disagree.  I'm wondering if perhaps a parallel module would make the most sense.  Then each field could have a type (native type, what gets stored), validators (what's allowed in that field), and a displayFormat (how to show it to the user).

I was trying to save code by incorporating it in type, but you're right that it doesn't really belong there.  I'll take another cut.

**Comment by jagi** [comment]
Hmm maybe it's a good idea to have some kind of a Blaze helper? It's related with VIEW layer. So it could format numbers to a given precise and add some suffix. Just an idea. I think that the more atomic are astronomy modules then better. I wouldn't like to put too much features in main package. Some people complained on the autoforms package that it's too heavy. I would like people to allow choosing like 10 astronomy modules that will give then all needed features.

**Comment by dovrosenberg** [comment]
Agree. I've started it as a new module package. Will share soon.

**Comment by dovrosenberg** [comment]
Published in https://github.com/dovrosenberg/meteor-astronomy-displayFormat

**Pull request closed without merging**
