### PR TITLE
Equal and Not Equal validators compare dates properly

### PR DESCRIPTION
**Pull request by peterchoo**
If both value and param are instances of dates, to compare equality we need to call `.getTime()`: http://stackoverflow.com/a/493018/1389202

### CODE REVIEW

**Comment by lukejagodzinski** [comment]
Yes in deed it does not work with dates however better solution would be using the `valueOf` method which returns "plain/primitive" value from object, thanks to that it will work not only with Date objects but also with Number, String, Boolean etc.

``` js
var d1 = new Date(2000, 0, 1);
var d2 = new Date(2000, 0, 1);
d1 === d2 // false
d1.valueOf() === d2.valueOf() // true

var n1 = new Number(5);
var n2 = new Number(5);
n1 === n2 // false
n1.valueOf() === n2.valueOf(); // true
```

The problem is when to use `valueOf` and when do not. As every object has the `valueOf` method we could just use it for all values. However as I think about equality people may want to compare two objects. If references are the same then they will be equal but what about same objects but with not the same reference.

``` js
var o1 = {a: 'a'};
var o2 = {a: 'a'};
o1 === o2 // false
o1.valueOf() === o2.valueOf() // false
```

They should be equal. So in some situations we should use `EJSON.equals()`. Or maybe we should use it in all possible cases.

``` js
EJSON.equals(5, 5) // true
EJSON.equals({a: 'a'}, {a: 'a'}) // true
EJSON.equals(Number(5), Number(5)) // true
```

**Comment by peterchoo** [comment]
I'm happy to update the PR to use `EJSON.equals()` and `!EJSON.equals()` as it is a very comprehensive check. Should I go ahead and do that?

**Comment by peterchoo** [comment]
I've updated the PR to use `EJSON.equals`

**Comment by lukejagodzinski** [comment]
Ok thanks! I just have to make sure that it works in all most common use cases and I will merge it

**Comment by peterchoo** [comment]
Hi @jagi,

Thanks, I appreciate you looking into this.  

It may be impertinent to ask, but will you be able to release this as 2.0.2?  This is required for our application, along with another fix for setting non plain objects (i.e. `this.set('start', new Date())` is not causing `isModified()` to return true.  I believe this was fixed in a16ff415cbfd651e81c4cbfb53c2115508e9c986 ).

**Comment by lukejagodzinski** [comment]
I can probably release it as 2.1 tomorrow. I can spend some time on Astronomy as it took me quite a lot of time from 2.0 release. Maybe this week is a good time to release 2.1.

**Pull request merged**
