### PR TITLE
Properly resolve subclass fields

### LINKED ISSUE #464: Subclass attributes undefined when queried by their parent class
Hi!

Only since my last update attributes of instances of subclasses are set to `undefined` when they were queried by their parent class. For example like `let child = Parent.findOne({_id: childId})`leads to `child.childAttribute === undefined`, when `childAttribute` is set and defined in the fields of the `Child = Parent.inherit(…` class. Is this intended?

Many thanks, great Work!

### PR DESCRIPTION
**Pull request by joefru**
To properly resolve fields of subclasses, you basically just needed to check for `typeField` before calling `resolveValues()` from within `transformToClass`

This should fix #464

### CODE REVIEW

**Comment by lukejagodzinski** [comment]
What for is that change? I don't see any reason to introduce it.

**Comment by joefru** [comment]
This change fixes the issue described in #464 where documents of a subclass have null field values when queried using `find()` on the parent class.  I'm not sure how to better explain. Somebody even posted a reproduction repository link in the issue comments.

**Comment by lukejagodzinski** [comment]
The problem is that I don't see fixing anything. I can't check it right now but when I look at it, it just gets type field from raw document instead of resolved one which does not make any difference. And if it does that mean it's a bug which should be fixed in the resolveValues method in the first place. So I will check it out, later today.

**Comment by joefru** [comment]
I'll let you check it out, but it most certainly makes a difference. Your algorithm is out-of-order. You need to resolve values using the subclass. To do that, you need to check for subclass (i.e. `typeField`) before resolving values. Otherwise, if you always resolve values with the parent class, `resolveValues` method will nullify fields defined in the subclass. There may be other ways to accomplish this, but my fix made most sense to me and works well.

Hope that makes sense. Astronomy is **outstanding**. Keep it up!

**Comment by lukejagodzinski** [comment]
I see, you're right. Merging, thanks!

**Pull request merged**
