### PR TITLE
Allow retrieving list of values from an Enum type

### PR DESCRIPTION
**Pull request by axelvaindal**
This PR introduce a new function `getValues` which return every values used to construct the Enum during the declaration process.

This is the implementation of #668.

### CODE REVIEW

**Comment by lukejagodzinski** [comment]
Thanks! Merging

**Comment by axelvaindal** [comment]
My pleasure 🙂.

@lukejagodzinski Do you know when the new version of Astronomy is going to be (with this PR included) ?

**Comment by lukejagodzinski** [comment]
Probably today or tomorrow, so stay tuned. I will inform you here when the new version is published

**Comment by eviatarkhen** [comment]
Installed the package today (it installed 2.5.6) but it looks like the getValues() function, is not recognized: TypeError: UserRole.getValues is not a function.
Was the new version published?

**Comment by lukejagodzinski** [comment]
@eviatarkhen sorry forgot to publish the new version. Did it just now. You can update to 2.5.7

**Comment by eviatarkhen** [comment]
Thanks, appreciating the fast response.

**Pull request merged**
