### PR TITLE
Typo and example fixes

### PR DESCRIPTION
**Pull request by dandv**
Proofread and reviewed the README.

There are a few issues to fix after accepting the PR:

* The Constructor documentation could be clarified. I gave it a shot, but I suspect there's more precise information that could be added regarding the parameters.
* The examples in the Global Events section won't work, I think, because of the direct assignment, instead of using `set`.

### CODE REVIEW

**Comment by jagi** [comment]
Oh thanks for so many fixes :-). I will review it when I'm back (in 10 days).

**Comment by jagi** [comment]
Ok merge. Thanks again for proofreading and review!

**Comment by dandv** [comment]
No problem.

How about my point #2 above, re. the Global Events example?

**Comment by jagi** [comment]
Yes you're right. I will update readme. Thanks

**Pull request merged**
