### PR TITLE
Add example of using doc.raw() without parameters

### PR DESCRIPTION
**Pull request by james1293**
Feedback is welcome!

### CODE REVIEW

**Comment by lukejagodzinski** [comment]
Hi, thanks for the PR. I will definitely merge it as we need more examples in docs. However, could you change one word in this commit?

> You can use it to get a raw copy of the entire ~~class~~ **document**, or a copy of

**Comment by james1293** [comment]
I added a new commit. I'm still new to git etiquette; should I instead start a new commit so that all of the PR's changes are in a single commit? Thanks!

**Comment by lukejagodzinski** [comment]
> I added a new commit. I'm still new to git etiquette; should I instead start a new commit so that all of the PR's changes are in a single commit? Thanks!

Yes right, it's just better to start a new PR with the final version :) so if it's not a problem for you, then please create a new one, thanks :)

**Comment by james1293** [comment]
Will do right now, thanks for letting me know!

**Pull request closed without merging**
