### PR TITLE
Casting docs: undefined and null are not casted

### PR DESCRIPTION
**Pull request by james1293**
As far as I can tell, this is true. If it's not, let me know, thanks!

### CODE REVIEW

**Comment by lukejagodzinski** [comment]
I don't think it's relevant. It's quite obvious that `null` and `undefined` values shouldn't be casted.

**Comment by james1293** [comment]
Perhaps it is obvious. I previously (mistakenly) thought that in required fields, they would be cast like empty strings, i.e.

```js
item.set('number', null, {cast: true});  // would cast to 0
item.set('boolean', null, {cast: true}); // would cast to false
item.set('string', null, {cast: true});  // would cast to ''
```

Also, this phrase appears in the "Casting Values" section: "There are also several nice tricks for easier casting of values coming from the forms, like the "FALSE" string will be casted to the `false` value".

IMO, that could be interpreted as casting the way I described. 

But either way is ok. :smiley:

**Comment by lukejagodzinski** [comment]
I know that it seems to be natural to cast `null` and `undefined` in a case of the `boolean` type for instance. However, `null` or `undefined` is the lack of value and if you get somehow `null` or `undefined` value from the form that means that there is no input field in the form.

Moreover, even if I would like to change that and allow casting `null` and `undefined` values for the required fields that would be a compatibility breaking change.

**Comment by lukejagodzinski** [comment]
Ok, I will merge your docs change to make it clear. Thanks

**Comment by james1293** [comment]
Thank you, I appreciate it!

Certainly no need to make any breaking changes; people can write their own casting functions if they want that behavior.

**Pull request merged**
