### PR TITLE
Allow to define Meteor methods in Class

### PR DESCRIPTION
**Pull request by Faberle**
https://github.com/jagi/meteor-astronomy/issues/470

### CODE REVIEW

**Comment by Faberle** [comment]
I tried to stick to your structure as closely as possible

**Comment by lukejagodzinski** [comment]
Thanks for a great job. I will review it probably during a weekend. One thing I've noticed after quickly reading through the code is that you're using `Meteor.methods` to define methods which will not work in some cases. One example is when you have collection coming from another meteor server, so connection object is not the default one. You can see how I did it using `Collection.connection` in the storage module, take a look here https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/storage/hooks/apply_definition.js#L57. So would be great if you could fix it.

Another thing is that for the method name you're using `let meteorMethodName = className + "/" + methodName;` which is ok but to avoid name collisions I would add extra `Astronomy/` prefix as all Astronomy methods. So it will be more concise.

Another thing is making sure that no one tries to redefine already existing methods, take a look here: https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/methods/hooks/parse_definition.js#L29

I know that I have no guide about creating modules but you should use the `wrapMethodInMeteor` method in the `applyDefinition` hook and not in the `parseDefinition` hook. The way you did it know will break inheritance. But that's my bad that I don't have any guide why each of these hooks exist.

I have also take a deeper look at how you actually call methods but so far it's looks correct beside calling method from `Meteor.call` and not from the Collection's connection :)

Thanks again for your work on this feature :)

**Comment by Faberle** [comment]
Thank you for creating such an awesome plugin in the first place! I'm currently fixing the things you mentioned, but I realized that it still needs some work when it comes to inheritance.

Do you think I should create a general "/Astronomy/execute" method and pass the class name and method as parameters, or create individual meteor methods for each Class?

I will continue working on it tomorrow :)
(Current State: https://github.com/Faberle/meteor-astronomy/commit/03a168e3a044993aab43ff14b5ce25619e2ddd8e)

**Comment by lukejagodzinski** [comment]
> I'm currently fixing the things you mentioned, but I realized that it still needs some work when it comes to inheritance.

If you have problem with inheritance it's probably because of wrapping methods in the `parseDefinition` hook.

> Do you think I should create a general "/Astronomy/execute" method and pass the class name and method as parameters, or create individual meteor methods for each Class?

Hmm seems to be a good idea, it will take far less memory to declare all methods and ultimately make application faster.

If you have any questions about how stuff work internally just ask. I'm glad that you're helping implement new features!

**Comment by Faberle** [comment]
I now switched to using just one method, but I don't know where I should hide the original method. 

What do you think about hiding them in the schema: 
(in the meteor method:)

``` javascript

                let classInstance = global.Astro.Class.classes[className];
                //fetch the object
                let obj = classInstance.findOne({_id: id});

                //get the method
                let method = classInstance.schema._meteorMethods[methodName];
```

Because I just use 1 meteor method I can't hide it in the context anymore :D

**Comment by lukejagodzinski** [comment]
Ok great! Ok so I will explain you the philosophy behind schema and definition.
- Definition is just what you put into the `Class.create()` method, so it's user defined definition of the class. Extend definition can also be provided in the `Class.inherit()` or `Class.extend()` methods.
- Every definition gets parsed. Parsing in Astronomy is a process of transforming "user defined" definition into definition that is Astronomy friendly. For example, when you have fields definition:

``` js
fields: {
  firstName: String
}
```

The `parseDefinition` hook is responsible for transforming such definition into sth like this:

``` js
fields: {
  firstName: {
    type: String
  }
}
```

Parsed definition is stored in the `Class.definition` property of each class (`Post.definition` etc.).
- Schema is where you store wrapped/transformed data from definition. In case of fields it stores fields' definitions converted to object of proper class like `ScalarField`, `ObjectField` or `ListField`. But in most cases data from definition is just copied to schema if it needs to be done. If you have method like `Class.getMethods()` then you should store methods not only in definition but also in schema.

So in case of the `meteorMethods` module you should just copy all methods from `definition.meteorMethods` to `schema.meteorMethods`. And as you have one Meteor method to execute all `meteorMethods` then you don't have to wrap each individual method when saving to `schema.meteorMethods`. So definition `definition.meteorMethods` == `schema.meteorMethods`. You can wrap methods on the fly but of course you can wrap them. Everything depends on how you want to implement it.

**Comment by lukejagodzinski** [comment]
Why did you introduce `_meteorMethods` property in definition and schema and set it as reserved word? There is not need for doing os.

**Comment by Faberle** [comment]
I need to keep a reference to the actual method somewhere. If I have the following setup:

``` javascript
const User = Class.create({
  name: 'User',
  /* ... */
  fields: {
    name: String
  },
  meteorMethods: {
    setName(newName) {
      this.name = newName;
      this.save();
    }
  }
});

let tmpUser = User.findOne();
```

I can now call `tmpUser.setName("Tom")` and it will execute `setName` as a Meteor method. In order to "find" the actual method again I save it under `_meteorMethods`

**Comment by lukejagodzinski** [comment]
You can just save it in the `schema.meteorMethods` and later access them `Class.schema.meteorMethods`

**Comment by Faberle** [comment]
Ah, so that's what you meant by wrapping on the fly 🙂 I will change it 2mrrw morning

**Comment by lukejagodzinski** [comment]
Ok cool :). I can also work on it right now. So we can merge it into some branch and work on it together :)

**Comment by lukejagodzinski** [comment]
Ok, as you can see I've merged your changes into the `feature/meteorMethods` branch. I will review it and eventually add or fix some code if needed. You can create future PR and push it into this branch.

**Comment by lukejagodzinski** [comment]
I think about one feature that would be handy. Right now the `this` context is a document which is nice and is the same as in regular Astronomy methods. However, when you're creating your own methods that wrap some Astronomy code you would have access to the `this` context of the Meteor method. So you can do `this.isSimulation`, `this.userId` or `this.unblock()` which are very handy. However you also need to have access to actual document, so I would pass it as the first argument:

``` js
meteorMethods: {
  changeName(doc, firstName, lastName) {
    this.unblock();
    doc.firstName = firstName;
    doc.lastName = lastName;
  }
}
```

The question is also if it should save document automatically or you would need to call `doc.save()` at the end of a method.

**Comment by Faberle** [comment]
A very good point. But I would actually go the other way and add the context of the meteor methods as the last argument of the method

``` javascript
meteorMethods: {
  changeName(firstName, lastName, meteorContext) {
    meteorContext.unblock();
    this.firstName = firstName;
    this.lastName = lastName;
  }
}
```

Because then the method can be written in the same way as a normal method.
I would also refrain from always calling `this.save()` because not all methods necessarily change the document. Some might simply retrieve information that wasn`t available on the client.

**Comment by lukejagodzinski** [comment]
@Faberle yes seems to be a good idea

**Pull request merged**
