### PR TITLE
Fix unresolved variable

### PR DESCRIPTION
**Pull request by krizka**
Here, I have error while trying to apply typeField

### CODE REVIEW

**Comment by jagi** [comment]
I can't merge this PR as changed a lot when implementing modules in Astronomy, so my current version of this file is different. What error do you have when using the `typeField`? So I will test it out.

**Comment by krizka** [comment]
Just use typeField somewhere. It's unresolved variable error on typeField, the fix is pretty simple, just use this line:
```const typeField = schema.typeField = parsedDefinition.typeField;```
or something similar to define typeField variable

**Comment by krizka** [comment]
By the way, the one more request to think about? Additional to typeField option, like collectionType, or typeName, which will differ from actual type name.
Imagine, I migrate, and have collection `conversations` with types `user` and `group` inside, but also I have User type. So I need the method to set same type-name for different collections. Or name types different for code and db. I hope, I wrote it clear to understand =)

**Comment by jagi** [comment]
Ok in deed there was an error. I've fixed it but still can't publish it as I'm waiting for information from MDG how to support Meteor 1.2 in packages made for Meteor 1.3 and using ES modules

**Comment by krizka** [comment]
Thanks! Yeah, its the same for me why I'm not pulling my local v2 anymore.

**Pull request closed without merging**
